name: timemachine-demo
channels:
  - conda-forge
  - openeye
dependencies:
  - python=3.7
  - jax=0.3.14
  - jaxlib=0.3.14=cpu*
  - mdtraj
  - openeye-toolkits=2020.2.0
  - openmm=7.5.1
  - pip:
    - diskcache
    - graphviz
    - jupyter-black
    - jupyterlab
    - git+https://github.com/proteneer/timemachine.git@70aef22
    - tqdm
